// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZSZYIp1bZ-WmIQY2yi12Ak9J9PokWl_A',
    appId: '1:1006177549674:web:f5dd37b319ec08e6a43913',
    messagingSenderId: '1006177549674',
    projectId: 'my-easy-tutorial-12101921',
    authDomain: 'my-easy-tutorial-12101921.firebaseapp.com',
    storageBucket: 'my-easy-tutorial-12101921.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5so2Tmm4NQZhSqicT7p9di2TIJ5stQNg',
    appId: '1:1006177549674:android:112dbfbcb32b2a11a43913',
    messagingSenderId: '1006177549674',
    projectId: 'my-easy-tutorial-12101921',
    storageBucket: 'my-easy-tutorial-12101921.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYkTRGLAqrk9da7uah2lOCThjqCp7B8NE',
    appId: '1:1006177549674:ios:3fd0b4d04681528aa43913',
    messagingSenderId: '1006177549674',
    projectId: 'my-easy-tutorial-12101921',
    storageBucket: 'my-easy-tutorial-12101921.appspot.com',
    iosBundleId: 'com.example.firebaseSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYkTRGLAqrk9da7uah2lOCThjqCp7B8NE',
    appId: '1:1006177549674:ios:3d8e07a680626c91a43913',
    messagingSenderId: '1006177549674',
    projectId: 'my-easy-tutorial-12101921',
    storageBucket: 'my-easy-tutorial-12101921.appspot.com',
    iosBundleId: 'com.example.firebaseSample.RunnerTests',
  );
}
